version: 0.2

environment_variables:
  plaintext:
    BUCKET: "loveis.blue"

phases:
  install:
    commands:
      - "echo Installing dependencies..."
      - npm install
  build:
    commands:
      - "echo Build started on `date`"
      - npm run build
      - "echo Build completed on `date`"

  post_build:
    commands:
      - "echo Deploying site to prod"
      - aws s3 sync --delete dist s3://$BUCKET --cache-control max-age=3600